### PR TITLE
add support for lines, basic styles

### PR DESCRIPTION
**Pull request by morandd**
this adds support for lines and all geometric primitives.

- uses SVGO as you suggested
- uses SVG2 Path interface polyfill to maniupate paths
- introduce THREE.MeshLine to render lines and polygons outlines
- support arcs and curves 
- support rect/circle/line/polygon/polyline SVG elements
- new example

i may have borked the build process a bit so feel free to hack that back into shape.

### CODE REVIEW

**Comment by morandd** [comment]
@7dir  ping

**Comment by 7dir** [comment]
basic example broken
```
Uncaught Error: Component attempted to register before AFRAME was available.
    at Object.107../path-data-polyfill.es5.js (build.js:58160)
    at s (build.js:1)
    at e (build.js:1)
    at build.js:1
```

**Comment by 7dir** [comment]
code looks like *****

**Comment by 7dir** [comment]
so we should separate version with SVGo and w/o it
size become too big

**Comment by 7dir** [comment]
@morandd ping

**Comment by morandd** [comment]
cleaned up code a bit & tried to fix the example. 

I find the build toolchain daunting (ES6/ES5 cross-compiling, minification, browserify "-x" flag, etc) so apologies if the example doesn't run smoothly and that the .min.js is not small.
  
It is probably feasible to drop SVGO. The only thing it's doing is converting <rect>, <circle>, and a few other primitives into <path> tags. It's not much more code to parse these primitives in extractSVGPaths(). We just need to convert the <rect>,<circle> etc tags into <path d="blah blah..."> tags and return those synthetic <path> tags along with the rest of the stuff from extractSVGPaths. Probably 10-30 lines of code.

I've got this running well enough for my needs right now so probably I won't contribute much more for now.

**Comment by 7dir** [comment]
I thought use SVGO convert svg as services or/and cli command. Put SVGO inside package ... dirty style )))

Going review code.

@morandd thanks

PS
Could I ask you some help? Maybe later?

**Comment by morandd** [comment]
not dirty style, with SVG inside the component simply works. one <script> tag and anyone can use it.  

handling <rect>, <circle> etc tags is not hard, that is the nice solution. That is the only thing SVGO is doing currently.

yes I can help in the future, no worries. I may get inspired to do the  primitive tags when I have time

**Pull request merged**
